#!/usr/bin/env bash
set -ex

cd /tmp
curl -L http://mirrors.sonic.net/apache/kafka/0.8.2.1/kafka_2.11-0.8.2.1.tgz > kafka_2.11-0.8.2.1.tgz
tar xvf kafka_2.11-0.8.2.1.tgz
cd kafka_2.11-0.8.2.1
bin/kafka-server-start.sh -daemon config/server.properties
