#!/usr/bin/env bash
set -ex

cd /tmp
curl http://mirrors.sonic.net/apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz > zookeeper-3.4.6.tar.gz
tar xvf zookeeper-3.4.6.tar.gz
cd zookeeper-3.4.6
cp conf/zoo_sample.cfg conf/zoo.cfg
bin/zkServer.sh start
